export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const FIRSTTIME = "FIRSTTIME";

export const RESTAURANT_INFORMATION_FILLED_SUCCESS ="RESTAURANT_INFORMATION_FILLED_SUCCESS";
export const RESTAURANT_INFORMATION_FILLED_FAILED ="RESTAURANT_INFORMATION_FILLED_FAILED";
export const CLEAR_RESTAURANT_MESSAGE ="CLEAR_RESTAURANT_MESSAGE";


// MENU RELATED
export const MENUITEMS_FETCHED_SUCCESS ="MENUITEMS_FETCHED_SUCCESS";
export const MENUITEMS_FETCHED_FAILED ="MENUITEMS_FETCHED_FAILED";
export const MENUITEM_CREATE_SUCCESS ="MENUITEM_CREATE_SUCCESS";
export const MENUITEM_CREATE_FAILED ="MENUITEM_CREATE_FAILED";
export const MENUITEM_UPDATE_SUCCESS ="MENUITEM_UPDATE_SUCCESS";
export const MENUITEM_UPDATE_FAILED ="MENUITEM_UPDATE_FAILED";
export const MENUITEM_DELETE_SUCCESS ="MENUITEM_DELETE_SUCCESS";
export const MENUITEM_DELETE_FAILED ="MENUITEM_DELETE_FAILED";
export const CLEAR_MENU_MESSAGE ="CLEAR_MENU_MESSAGE";

// Category Related

export const CATEGORYS_FETCHED_SUCCESS = "CATEGORYS_FETCHED_SUCCESS";
export const CATEGORYS_FETCHED_FAILED = "CATEGORYS_FETCHED_FAILED";
export const CATEGORY_ADD_SUCCESS ="CATEGORY_ADD_SUCCESS"
export const CATEGORY_ADD_FAILD="CATEGORY_ADD_FAILD";
export const CATEGORY_UPDATE_SUCCESS ="CATEGORY_UPDATE_SUCCESS";
export const CATEGORY_UPDATE_FAILED ="CATEGORY_UPDATE_FAILED";
export const CATEGORY_DELETE_SUCCESS ="CATEGORY_DELETE_SUCCESS";
export const CATEGORY_DELETE_FAILED ="CATEGORY_DELETE_FAILED";
export const CLEAR_CATEGORY_MESSAGE ="CLEAR_CATEGORY_MESSAGE";


// Order Related


export const ORDER_FETCHED_SUCCESS = "ORDER_FETCHED_SUCCESS";
export const ORDER_FETCHED_FAILED ="ORDER_FETCHED_FAILED"
export const ORDER_ACCEPT_SUCCESS="ORDER_ACCEPT_SUCCESS"
export const ORDER_ACCEPT_FAILED = "ORDER_ACCEPT_FAILED"
export const ORDER_REJECT_SUCCESS ="ORDER_REJECT_SUCCESS"
export const ORDER_REJECT_FAILED ="ORDER_REJECT_FAILED"
export const ORDER_CHANGE_STATUS_SUCCESS ="ORDER_CHANGE_STATUS_SUCCESS"
export const ORDER_CHANGE_STATUS_FAILED ="ORDER_CHANGE_STATUS_FAILED"
export const CLEAR_ORDER_MESSAGE ="CLEAR_ORDER_MESSAGE"



// Customer Related

export const CUSTOMER_FETCHED_SUCCESS = "CUSTOMER_FETCHED_SUCCESS";
export const CUSTOMER_FETCHED_FAILED ="CUSTOMER_FETCHED_FAILED"
export const CUSTOMER_BLOCK_SUCCESS="CUSTOMER_BLOCK_SUCCESS"
export const CUSTOMER_BLOCK_FAILED = "CUSTOMER_BLOCK_FAILED"
export const CLEAR_CUSTOMER_MESSAGE ="CLEAR_ORDER_MESSAGE"



// Employee Related


export const EMPLOYEES_FETCHED_SUCCESS = "EMPLOYEES_FETCHED_SUCCESS";
export const EMPLOYEES_FETCHED_FAILED = "EMPLOYEES_FETCHED_FAILED";
export const EMPLOYEE_ADD_SUCCESS ="EMPLOYEE_ADD_SUCCESS"
export const EMPLOYEE_ADD_FAILD="EMPLOYEE_ADD_FAILD";
export const EMPLOYEE_EDIT_SUCCESS ="EMPLOYEE_EDIT_SUCCESS";
export const EMPLOYEE_EDIT_FAILED ="EMPLOYEE_EDIT_FAILED";
export const EMPLOYEE_DELETE_SUCCESS ="EMPLOYEE_DELETE_SUCCESS";
export const EMPLOYEE_DELETE_FAILED ="EMPLOYEE_DELETE_FAILED";
export const CLEAR_EMPLOYEE_MESSAGE ="CLEAR_CATEGORY_MESSAGE"


// Restaurant Account Related profile 
export const RESTAURANT_INFO_FETCHED_SUCCESS = "EMPLOYEES_FETCHED_SUCCESS";
export const RESTAURANT_INFO_FETCHED_FAILED = "EMPLOYEES_FETCHED_FAILED";
export const ACCOUNT_INFO_FETCHED_SUCCESS = "ACCOUNT_INFO_FETCHED_SUCCESS"
export const ACCOUNT_INFO_FETCHED_FAILED = "ACCOUNT_INFO_FETCHED_FAILED"
export const ACCOUNT_INFO_EDIT_SUCCESS = "ACCOUNT_INFO_EDIT_SUCCESS"
export const ACCOUNT_INFO_EDIT_FAILED = "ACCOUNT_INFO_EDIT_FAILED"
export const SHARED_COST_INFO_FETCHED_SUCCESS = "SHARED_COST_INFO_FETCHED_SUCCESS"
export const SHARED_COST_INFO_FETCHED_FAILED = "SHARED_COST_INFO_FETCHED_FAILED"
export const SHARED_COST_INFO_EDIT_SUCCESS = "SHARED_COST_INFO_EDIT_SUCCESS"
export const SHARED_COST_INFO_EDIT_FAILED = "SHARED_COST_INFO_EDIT_FAILED"




