export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const FIRSTTIME = "FIRSTTIME";

export const RESTAURANT_INFORMATION_FILLED_SUCCESS ="RESTAURANT_INFORMATION_FILLED_SUCCESS";
export const RESTAURANT_INFORMATION_FILLED_FAILED ="RESTAURANT_INFORMATION_FILLED_FAILED";

// MENU RELATED
export const MENUITEMS_FETCHED_SUCCESS ="MENUITEMS_FETCHED_SUCCESS";
export const MENUITEMS_FETCHED_FAILED ="MENUITEMS_FETCHED_FAILED";
export const MENUITEM_CREATE_SUCCESS ="MENUITEM_CREATE_SUCCESS";
export const MENUITEM_CREATE_FAILED ="MENUITEM_CREATE_FAILED";
export const MENUITEM_UPDATE_SUCCESS ="MENUITEM_UPDATE_SUCCESS";
export const MENUITEM_UPDATE_FAILED ="MENUITEM_UPDATE_FAILED";
export const MENUITEM_DELETE_SUCCESS ="MENUITEM_DELETE_SUCCESS";
export const MENUITEM_DELETE_FAILED ="MENUITEM_DELETE_FAILED";
export const CLEAR_MENU_MESSAGE ="CLEAR_MENU_MESSAGE";

// Category Related

export const CATEGORYS_FETCHED_SUCCESS = "CATEGORYS_FETCHED_SUCCESS";
export const CATEGORYS_FETCHED_FAILED = "CATEGORYS_FETCHED_FAILED";
export const CATEGORY_ADD_SUCCESS ="CATEGORY_ADD_SUCCESS"
export const CATEGORY_ADD_FAILD="CATEGORY_ADD_FAILD";
export const CLEAR_CATEGORY_MESSAGE ="CLEAR_CATEGORY_MESSAGE";
            